from enum import Enum

class UT(Enum):
    ATENCION = 1,
    REQUERIMIENTO = 2,
    SOLUCIONDEPROBLEMAS = 3,
    TRANSACCIONCOMPRAS = 4,
    IMPLEMENTACIONDEAPOYO = 5,
    PLATAFORMASDIGITALES = 6,
    RECEPCIONVEHICULO = 7,
    MANTENCIONVEHICULO = 8,
    REPARTIDOR = 9,
    SERVICIOENGENERAL = 10,
    SERVICIOPOSTVENTA = 11,
    RECEPCIONDEFACTURAS = 12,